### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by NiteshVLSI** [NiteshIIITB/IIIT_ASIC#2]
![yosys](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/abdfaa0a-5801-477e-8d73-dc2c873db915)
![yosys_show](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/7888d6c3-e880-4da1-b751-961ec80847b8)
![gtkwave](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/15fdb0a8-0544-42ec-9728-ccc504e13f57)
![gtkwave_show](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/8a86c9a3-9e0b-4685-882f-7aa89ffb799a)
![iverilog](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/5ee81e29-7172-4958-8619-d11be643f8be)
![iverilog_install](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/23e46cdd-5286-4ac5-bfa6-ed7c014c27e5)

**Comment by NiteshIIITB** [comment]
![mux_run](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/b7905394-3523-4174-aaaf-dcd6180b73e4)

**Comment by NiteshVLSI** [comment]
![mux_run](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/7856401e-6790-4f8a-95c0-bec59d68a400)

**Comment by NiteshVLSI** [comment]
![waveform](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/00235466-2269-4be8-a22e-83b48714f58f)

**Comment by NiteshVLSI** [comment]
![yosys1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/dd472df9-c279-445a-bf5f-d429a8363118)
![synth](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/8d30a21f-8e28-4dfe-8f37-b8f1a6007c69)
![Schematic](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/345e7d91-af15-4235-8964-740a850c34f7)
![gitclone](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/fb49dc3d-fd55-4d65-b31c-8b8fd15e8b4d)
![abc](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/2f8403a1-427e-4b63-98d5-b24ad5da08c1)

**Comment by NiteshVLSI** [comment]
![Schematic_r](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/a89d0297-30c1-4dc2-bb4e-b8231d8f99af)
![synth_r](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/7ad5f69c-1a2a-4e71-b9db-2006e45d6ae4)

**Comment by NiteshVLSI** [comment]
![3 1 5](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/e56d3b0a-c62f-4aa8-8ee8-e3639413283a)
![3 1 4](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/6f73b3ea-42e9-4892-ad7d-a3f398997ee0)
![3 1 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/1bcb75d8-8211-49a4-b5f9-2ef8657736d9)
![3 1 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/12282dc5-4d76-4a0f-a63e-4a9d4ffa91ff)
![3 1 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/92d0fe15-cdef-42db-a350-86de660efed7)

**Comment by NiteshVLSI** [comment]
![3 2 4](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/99d653b5-d7a8-4b20-8a71-58bfb12f3779)
![3 2 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/797f3127-2f63-4a37-b301-b01e8ccc37b9)
![3 2 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/01ceb27e-313c-4db7-b9f7-6baa33196c8d)
![3 2 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/138e3d4e-fb3e-4783-8c55-428f247ecade)
![3 1 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/1ac97316-85b8-4afc-8014-973fdf045292)

**Comment by NiteshVLSI** [comment]
![3 3 4](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/e7a02aa7-4375-4cdb-804f-5dcf59e4f884)
![3 3 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/0b0c6209-eb08-4c99-a629-5769e2915510)
![3 3 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/f1d5c12a-7256-4d0f-b182-af6f720f7760)
![3 3 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/e99d5ca1-ef36-433f-911a-b2946ffe1ad1)

**Comment by NiteshVLSI** [comment]
![3 4 4](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/1bb6a678-a2bd-4e41-a6ec-b80a85e643f9)
![3 4 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/89532985-6682-4ac8-82e6-0bf3b44cf340)
![3 4 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/b64da2ae-d83c-4745-81d8-b15d4844257d)
![3 4 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/62f9ad6c-d55e-4640-92ec-dfc092f3091e)

**Comment by NiteshVLSI** [comment]
![3 S 4 4](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/802853f2-a23b-49cc-8b11-95e30e8aaea5)
![3 S 4 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/44e68247-7336-4e8d-8c0b-1d7c127b27b8)
![3 S 4 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/30f42cde-230c-480f-932c-203534b869fd)
![3 S 4 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/bdb8da9f-772c-47db-b3c6-4158ace0fbde)
![3 S 3 5](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/03bf3231-0c3f-4bee-a0eb-f305b0b7c360)
![3 S 3 4](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/7ec479b8-72e0-4e59-ae6f-5b804ca1f82d)
![3 S 3 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/1928aaa8-362d-4d18-84ab-44e82e9e710c)
![3 S 3 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/4cc14a53-3fd9-4d7f-ab75-b6e9fc8c4ee6)
![3 S 3 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/7ec7056d-9de6-41ff-874f-4b5eb031c742)
![3 S 2 5](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/5a0b8868-501d-4a51-ac99-62bc55394426)
![3 S 2 4](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/1913366d-3a71-466f-90ef-811b718e08f2)
![3 S 2 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/fd49b7ce-a8f0-4b4d-9ec3-0433a1048c8f)
![3 S 2 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/0ae20c21-027e-4898-89a1-0775f25ee37a)
![3 S 2 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/2d1cc7d5-6e84-4544-9b49-f84d82951852)
![3 S 1 5](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/17b41794-01d8-4d37-a81a-2050dd6a420c)
![3 S 1 4](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/dfd9d2c6-832a-4304-ba8e-13c4576d142f)
![3 S 1 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/50caf946-cc97-481e-ab55-e827f1828589)
![3 S 1 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/8940d1d3-6c27-4857-8745-9ecc7e3695fe)

**Comment by NiteshVLSI** [comment]
![3 S 1 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/59f55bf4-6c76-4b3a-9d13-06a99ec810ff)

**Comment by NiteshVLSI** [comment]
![3 S 5 6](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/e507e91a-51d6-435b-ab76-94708f5e3a6b)
![3 S 5 5](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/e1592296-a2ce-419e-9568-818a8540d888)
![3 S 5 4](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/242511f8-c569-4188-9927-ed6af5636ccb)
![3 S 5 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/c82807db-af80-4091-92b0-80b71c6c231c)
![3 S 5 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/2c24121a-95d8-4f89-8ecd-ce499c96c425)
![3 S 5 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/5de50eb7-9a50-4671-9d60-3a93941854a5)

**Comment by NiteshVLSI** [comment]
![3 S 7 4](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/0ff9dd97-5f3a-4c21-ae2c-e7a0d541328d)
![3 S 7 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/054cf173-a2a3-4ea2-9d98-e260678ee1d2)
![3 S 7 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/9a5a9d34-eb83-44c4-ac72-be6e16d6870e)
![3 S 6 4](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/96f4f751-b26e-4f0e-b41a-b97b333d710e)
![3 S 6 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/2b444ba8-e5ab-4c1d-848e-054009d68b4f)
![3 S 6 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/fb2e7535-1b72-4ba4-8dfb-db3fa4388316)
![3 S 6 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/83d69d2c-cdf2-4a3e-94b9-e830f1170722)

**Comment by NiteshVLSI** [comment]
![d1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/db18752e-aca7-4411-b132-f7dbf4b4305c)

**Comment by NiteshVLSI** [comment]
![D2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/53f343c9-6fe2-4aea-95a8-7bdfcc7cb85e)

**Comment by NiteshVLSI** [comment]
![D4](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/211a2c04-860c-4c46-b032-fad1516d714f)
![D3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/db70ba57-c14e-43c2-8a18-7d337f026bcf)

**Comment by NiteshVLSI** [comment]
![DS1n2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/6fd58fb2-64f8-471f-996a-b12d34716161)

**Comment by NiteshVLSI** [comment]
![GLS](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/3e2ace43-f7af-49ca-9f2b-3d7be70d2f5c)

**Comment by NiteshVLSI** [comment]
![4 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/cc74a6dd-33e7-4b7a-9759-fd508deecac1)
![4 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/bef773de-ef9a-4ee0-9f6d-57c233252d4a)

**Comment by NiteshVLSI** [comment]
![4 6](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/5c80b013-eb52-48d0-bc30-bcf8cfa73407)
![4 5](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/b273d22b-812e-44c7-8738-85c2f724b28e)
![4 4](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/7c686de9-f315-4602-ac41-acd6b667d01f)
![4 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/07f37682-fcf0-4a54-af82-ba435884e486)

**Comment by NiteshVLSI** [comment]
![4 8](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/0b392370-3d62-408e-be6d-5f571bbd9407)
![4 7](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/70b64b4f-36d3-4553-acc3-010d232bfadf)

**Comment by NiteshVLSI** [comment]
![4 2 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/440f72af-7134-4338-b726-71a8e9489315)

**Comment by NiteshVLSI** [comment]
![4 2 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/0596be84-e741-49ec-a2d6-b1e600ab09cc)
![4 2 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/9915429c-d3bf-4937-8f1a-c0ee5e543bb5)
![4 2 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/7c426011-215c-403b-b0d9-f1cd5a0b6715)

**Comment by NiteshVLSI** [comment]
![4 2 4](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/a6a4d15d-f73b-46b6-ac62-b6e2ef29e6ee)

**Comment by NiteshVLSI** [comment]
![4 3 4](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/6fca2b0d-1ad0-48bb-9a20-08f70338b1ef)
![4 3 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/081ddfb7-c9ac-4e47-9936-a7069ee9bd9d)
![4 3 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/dd30c19c-c24b-4a62-863f-f8b6b6b68d8c)
![4 3 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/e390d1f2-80e0-4d72-9e59-7c3623265df9)

**Comment by NiteshVLSI** [comment]
![4 3 5](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/5e5b8d87-0f63-478c-a82e-3cf4b8fef572)

**Comment by NiteshVLSI** [comment]
![5 1 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/3d69c7a5-1fad-4715-bb9c-3b2440dcc2a2)
![5 1 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/b4c88c2d-d5fc-408b-9d39-a3cd35c8d5c0)
![5 1 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/7655ac13-3d1c-40e4-a7dd-a59953bdee11)

**Comment by NiteshVLSI** [comment]
![5 1 6](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/9f4e0e11-9b90-464e-9284-fe8d9964a733)
![5 1 5](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/2f0c632b-9e8c-4caa-864d-a367fa47ac1e)
![5 1 4](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/6698f39b-2399-4c71-a4f9-0c4629b19332)

**Comment by NiteshVLSI** [comment]
![5 3 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/aa2646cc-aa50-434e-a88b-946f7e7f8a2f)
![5 3 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/e7edee64-eac8-411e-8ee4-b43fc6d3c4cb)
![5 3 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/af3bfbd4-b434-4e79-ad90-bc99002adc0f)

**Comment by NiteshVLSI** [comment]
![5 4 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/b7f3c6db-5136-45ab-9f4f-93a1acc0c6df)
![5 4 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/5cfaa54a-503a-4084-b890-210cef96845a)
![5 4 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/7667b7cd-8668-432b-9239-49bbfee8e831)

**Comment by NiteshVLSI** [comment]
![5 5 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/0f009e41-472e-4eea-9d5c-4f3ec7a595ac)
![5 5 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/9c418c26-8de4-4368-9ebe-d1664514edbd)
![5 5 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/341e2c05-fe92-40be-82e7-1a51424ddb54)

**Comment by NiteshVLSI** [comment]
![5 6 4](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/1c29e6d8-cb8c-4df5-a4c7-ac89613d412d)
![5 6 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/6b035481-4c0e-4e21-87b2-8e841ffdf12e)
![5 6 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/697eb737-c7b5-4a44-a4ef-6b61cbe472c0)
![5 6 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/58a23e3d-d288-4d01-b2df-24094fcf830b)

**Comment by NiteshVLSI** [comment]
![5 7 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/be3db5ac-9fa6-4855-8571-bb695ea3db85)

**Comment by NiteshVLSI** [comment]
![5 7 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/345441ec-ff0a-48cb-921b-711937524a54)

**Comment by NiteshVLSI** [comment]
![5 7 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/3dea201d-411b-4cb1-b89f-33b742d2a97c)

**Comment by NiteshVLSI** [comment]
![5 8 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/e83fb946-ea2d-4cbd-abf5-76ae5a7854be)

**Comment by NiteshVLSI** [comment]
![5 8 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/76addbab-651c-4b73-bd5b-602f9b413ef0)
![5 8 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/7f020e5a-6d7c-430e-8d12-85513b32ba8d)

**Comment by NiteshVLSI** [comment]
![5 9 4](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/e22dd604-2d96-4e76-9e57-1b55cc6404e2)
![5 9 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/10128dc7-fd8f-4557-b83f-05a74673ff18)
![5 9 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/f28aefae-0fc6-44ca-8432-e23956b2e825)
![5 9 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/57969dd5-58c3-4a2e-8613-93513e5923e9)

**Comment by NiteshVLSI** [comment]
![2 2 2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/bc78d599-a838-4ab1-ad4e-733547915b55)
![2 2 1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/cb791c96-5179-4e08-95d7-3d317d89589d)

**Comment by NiteshVLSI** [comment]
![2 2 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/c5890537-c35f-4d5a-b526-d110ed5fb875)

**Comment by NiteshVLSI** [comment]
![2 2 6](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/4534d113-0d96-4c21-a477-95478c4e4c0b)
![2 2 5](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/b5f83732-a8ea-4fba-8145-ae18b1cfceea)
![2 2 4](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/11944f24-3f10-409b-8bfa-2ab6aa743d6b)
![2 2 3](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/b5d571a6-2039-4e06-b727-ab3fa81e3767)

**Comment by NiteshVLSI** [comment]
![2 2 9](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/76a56bb7-2e22-4c2f-86a0-1b4267fa5e6e)
![2 2 8](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/91757670-3e9f-473c-810d-c161561cdbd5)
![2 2 7](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/bb349ba1-bf86-4f55-bf56-3f6be8fc2cd7)

**Comment by NiteshVLSI** [comment]
![dffasr](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/38dec2c2-5992-4aff-be65-57b7bf204b62)

**Comment by NiteshVLSI** [comment]
![dffaset](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/71c448ad-5979-4f39-9cb0-9fdbdbce8d09)

**Comment by NiteshVLSI** [comment]
![dffsyncres](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/48abf7ee-91fc-40bd-82a8-9ff5df6c69ce)

**Comment by NiteshVLSI** [comment]
![dffasyncres_synth](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/0162676b-f7bc-4568-85d2-01f515453fce)
![dffasynchres_synth1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/d94c098c-6cf6-4d6d-bc9e-505278ad3807)

**Comment by NiteshVLSI** [comment]
![dff sych set](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/8af057f8-eaa4-4d93-9e49-e4e0927d4347)
![dff_async_set](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/31247dc8-a41a-49ae-9088-4a0d03fc20fa)

**Comment by NiteshVLSI** [comment]
![dffsyncres_syn](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/54fb5cc9-24c0-411a-92da-2ef6f4c90959)
![dffsyncres_sy](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/737d2b46-4e49-46bd-81b3-7edccbd58311)

**Comment by NiteshVLSI** [comment]
![1](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/cf43ddf2-dbde-42c3-b750-8be58eca7d97)

**Comment by NiteshVLSI** [comment]
![2](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/7192eedd-6ec6-49a3-8bf2-4d0890d9cb8f)

**Comment by NiteshVLSI** [comment]
![0](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/7daa747e-7bd9-4a02-9704-e0c080ce5da1)

**Comment by NiteshVLSI** [comment]
![Screenshot from 2023-08-15 21-04-55](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/1d10ac1d-37d0-4d77-954d-b58d2b16e471)

**Comment by NiteshVLSI** [comment]
![D5](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/c894385f-ac13-49a8-8f56-1417ec720c2d)

**Comment by NiteshVLSI** [comment]
![Screenshot from 2023-08-15 21-16-33](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/514cb3a7-8699-4b14-b435-1ec6ca4bf4f2)

**Comment by NiteshVLSI** [comment]
![Screenshot from 2023-08-15 21-19-43](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/d56ce6ad-03b3-40fd-b071-7651a6b15b7c)

**Comment by NiteshVLSI** [comment]
![Screenshot from 2023-08-15 21-27-42](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/d3308aa4-95f6-458b-930e-d46a08f88fac)

**Comment by NiteshVLSI** [comment]
![Screenshot from 2023-08-15 21-30-00](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/bc8458b9-2b77-42ec-a36d-8c0d5aaee349)

**Comment by NiteshVLSI** [comment]
![Screenshot from 2023-08-15 21-31-43](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/1764610b-045b-439f-830f-0973ca6b13a3)

**Comment by NiteshVLSI** [comment]
![Screenshot from 2023-08-15 21-33-08](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/a0c329bc-c9a8-4e32-a792-37c78dbf1e03)

**Comment by NiteshVLSI** [comment]
![Screenshot from 2023-08-15 21-53-29](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/e940a63f-6997-4d0f-a167-e75df369d456)

**Comment by NiteshVLSI** [comment]
![Screenshot from 2023-08-15 21-54-56](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/fe0ffc73-5ffb-42d3-bee3-420d2c70a126)

**Comment by NiteshVLSI** [comment]
![Screenshot from 2023-08-15 22-05-57](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/df1f9a52-6bb5-4d22-b4d5-c43eeaf915a0)

**Comment by NiteshVLSI** [comment]
![Screenshot from 2023-08-15 22-07-30](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/49559c7d-9503-4fbb-be85-e8fd0902c48d)

**Comment by NiteshVLSI** [comment]
![Screenshot from 2023-08-15 22-20-18](https://github.com/NiteshIIITB/IIIT_ASIC/assets/140998787/c64743c0-6940-4ba5-8de1-354b892c8e78)
